/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatFeedback {
  'customer' : Principal,
  'submittedAt' : bigint,
  'comment' : string,
  'sessionId' : bigint,
  'rating' : bigint,
}
export interface ChatMessage {
  'content' : string,
  'messageId' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : bigint,
  'delivered' : boolean,
  'attachment' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface KBArticle {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'updatedAt' : bigint,
  'viewCount' : bigint,
  'category' : KnowledgeCategory,
}
export type KnowledgeCategory = { 'NetworkConnectivity' : null } |
  { 'AccountPasswords' : null } |
  { 'GeneralSupport' : null } |
  { 'WindowsSupport' : null } |
  { 'SoftwareSupport' : null } |
  { 'HardwareSupport' : null } |
  { 'PrintersPeripherals' : null };
export interface LoginEvent {
  'name' : string,
  'role' : string,
  'email' : string,
  'timestamp' : bigint,
  'principalId' : string,
}
export type MessageStatus = { 'success' : null } |
  { 'failed' : string };
export interface PaymentRecord {
  'status' : PaymentStatus,
  'customer' : Principal,
  'currency' : string,
  'paymentId' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportTicket {
  'status' : TicketStatusOld,
  'technician' : Principal,
  'customer' : Principal,
  'messages' : Array<ChatMessage>,
  'createdAt' : bigint,
  'feedback' : [] | [{ 'comment' : string, 'rating' : bigint }],
  'ticketId' : bigint,
  'updatedAt' : bigint,
}
export interface TechnicianAvailability {
  'technician' : Principal,
  'lastUpdated' : bigint,
  'isAvailable' : boolean,
}
export type TicketStatusOld = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'displayName' : string,
  'isTechnician' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addTicketFeedback' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTechnician' : ActorMethod<[bigint, Principal], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createKBArticle' : ActorMethod<
    [string, KnowledgeCategory, string, Array<string>],
    undefined
  >,
  'createPaymentRecord' : ActorMethod<[string, bigint, string], undefined>,
  'createSupportCheckoutSession' : ActorMethod<[string, string], string>,
  'createSupportTicket' : ActorMethod<[Principal], SupportTicket>,
  'deleteKBArticle' : ActorMethod<[bigint], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'getAdminTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getAllAvailableTechnicians' : ActorMethod<[], Array<TechnicianAvailability>>,
  'getAllKBArticles' : ActorMethod<[], Array<KBArticle>>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAnalyticsMetrics' : ActorMethod<
    [],
    {
      'resolutionRate' : bigint,
      'resolvedTickets' : bigint,
      'openTickets' : bigint,
      'totalTickets' : bigint,
    }
  >,
  'getArticlesByCategory' : ActorMethod<[KnowledgeCategory], Array<KBArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatFeedback' : ActorMethod<[bigint], [] | [ChatFeedback]>,
  'getKBArticle' : ActorMethod<[bigint], [] | [KBArticle]>,
  'getLoginEvents' : ActorMethod<[], Array<LoginEvent>>,
  'getLoginEventsCSV' : ActorMethod<[], string>,
  'getMessagesBetweenUsers' : ActorMethod<
    [Principal, Principal],
    Array<ChatMessage>
  >,
  'getPaymentRecord' : ActorMethod<[string], [] | [PaymentRecord]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTechnicianAvailability' : ActorMethod<
    [Principal],
    [] | [TechnicianAvailability]
  >,
  'getTicket' : ActorMethod<[bigint], [] | [SupportTicket]>,
  'getUserMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTickets' : ActorMethod<[], Array<SupportTicket>>,
  'incrementArticleViewCount' : ActorMethod<[bigint], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markMessagesAsRead' : ActorMethod<[Principal, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchKBArticles' : ActorMethod<[string], Array<KBArticle>>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [ExternalBlob]],
    MessageStatus
  >,
  'setAllTechniciansOffline' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTechnicianAvailability' : ActorMethod<[boolean], undefined>,
  'submitRating' : ActorMethod<[bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateKBArticle' : ActorMethod<
    [bigint, string, KnowledgeCategory, string, Array<string>],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<[string, PaymentStatus], undefined>,
  'updateTicketStatus' : ActorMethod<[bigint, TicketStatusOld], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];