/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const KnowledgeCategory = IDL.Variant({
  'NetworkConnectivity' : IDL.Null,
  'AccountPasswords' : IDL.Null,
  'GeneralSupport' : IDL.Null,
  'WindowsSupport' : IDL.Null,
  'SoftwareSupport' : IDL.Null,
  'HardwareSupport' : IDL.Null,
  'PrintersPeripherals' : IDL.Null,
});
export const TicketStatusOld = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Nat,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'delivered' : IDL.Bool,
  'attachment' : IDL.Opt(ExternalBlob),
});
export const SupportTicket = IDL.Record({
  'status' : TicketStatusOld,
  'technician' : IDL.Principal,
  'customer' : IDL.Principal,
  'messages' : IDL.Vec(ChatMessage),
  'createdAt' : IDL.Int,
  'feedback' : IDL.Opt(
    IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat })
  ),
  'ticketId' : IDL.Nat,
  'updatedAt' : IDL.Int,
});
export const TechnicianAvailability = IDL.Record({
  'technician' : IDL.Principal,
  'lastUpdated' : IDL.Int,
  'isAvailable' : IDL.Bool,
});
export const KBArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'viewCount' : IDL.Nat,
  'category' : KnowledgeCategory,
});
export const ChatTier = IDL.Variant({
  'sponsorship' : IDL.Null,
  'premium' : IDL.Null,
  'basic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'isTechnician' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const ChatFeedback = IDL.Record({
  'customer' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'comment' : IDL.Text,
  'sessionId' : IDL.Nat,
  'rating' : IDL.Int,
});
export const LoginEvent = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'principalId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'status' : PaymentStatus,
  'customer' : IDL.Principal,
  'currency' : IDL.Text,
  'paymentId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const ToggleStatus = IDL.Variant({
  'disabled' : IDL.Null,
  'enabled' : IDL.Null,
  'notRequested' : IDL.Null,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PaymentToggleState = IDL.Record({
  'technician' : IDL.Principal,
  'active' : IDL.Bool,
  'toggleEnabled' : IDL.Bool,
  'customer' : IDL.Principal,
  'paymentRequested' : IDL.Bool,
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const MessageStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addTicketFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTechnician' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createKBArticle' : IDL.Func(
      [IDL.Text, KnowledgeCategory, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createPaymentRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'createSupportCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSupportTicket' : IDL.Func([IDL.Principal], [SupportTicket], []),
  'deleteKBArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'endChatSession' : IDL.Func([IDL.Nat], [], []),
  'getAdminTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAllAvailableTechnicians' : IDL.Func(
      [],
      [IDL.Vec(TechnicianAvailability)],
      ['query'],
    ),
  'getAllKBArticles' : IDL.Func([], [IDL.Vec(KBArticle)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAnalyticsMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'resolutionRate' : IDL.Nat,
          'resolvedTickets' : IDL.Nat,
          'openTickets' : IDL.Nat,
          'totalTickets' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getArticlesByCategory' : IDL.Func(
      [KnowledgeCategory],
      [IDL.Vec(KBArticle)],
      ['query'],
    ),
  'getAvailableTiers' : IDL.Func([], [IDL.Vec(ChatTier)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatFeedback' : IDL.Func([IDL.Nat], [IDL.Opt(ChatFeedback)], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getKBArticle' : IDL.Func([IDL.Nat], [IDL.Opt(KBArticle)], ['query']),
  'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
  'getLoginEventsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'getMessagesBetweenUsers' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getPaymentRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentRecord)],
      ['query'],
    ),
  'getPersistentToggleState' : IDL.Func([IDL.Nat], [ToggleStatus], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportedCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTechnicianAvailability' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TechnicianAvailability)],
      ['query'],
    ),
  'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(SupportTicket)], ['query']),
  'getToggleState' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PaymentToggleState)],
      ['query'],
    ),
  'getUserMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'incrementArticleViewCount' : IDL.Func([IDL.Nat], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesAsRead' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'markTicketMessagesAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchKBArticles' : IDL.Func([IDL.Text], [IDL.Vec(KBArticle)], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob)],
      [MessageStatus],
      [],
    ),
  'sendMessageForTicket' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [MessageStatus],
      [],
    ),
  'setAllTechniciansOffline' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setTechnicianAvailability' : IDL.Func([IDL.Bool], [], []),
  'setToggleState' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitRating' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'tierSelectionInfo' : IDL.Func(
      [IDL.Nat, ChatTier, IDL.Bool],
      [IDL.Record({ 'paymentStatus' : IDL.Bool, 'tier' : ChatTier })],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateKBArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, KnowledgeCategory, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatusOld], [], []),
  'updateTierSelection' : IDL.Func([IDL.Nat, ChatTier], [ChatTier], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const KnowledgeCategory = IDL.Variant({
    'NetworkConnectivity' : IDL.Null,
    'AccountPasswords' : IDL.Null,
    'GeneralSupport' : IDL.Null,
    'WindowsSupport' : IDL.Null,
    'SoftwareSupport' : IDL.Null,
    'HardwareSupport' : IDL.Null,
    'PrintersPeripherals' : IDL.Null,
  });
  const TicketStatusOld = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Nat,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'delivered' : IDL.Bool,
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const SupportTicket = IDL.Record({
    'status' : TicketStatusOld,
    'technician' : IDL.Principal,
    'customer' : IDL.Principal,
    'messages' : IDL.Vec(ChatMessage),
    'createdAt' : IDL.Int,
    'feedback' : IDL.Opt(
      IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat })
    ),
    'ticketId' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const TechnicianAvailability = IDL.Record({
    'technician' : IDL.Principal,
    'lastUpdated' : IDL.Int,
    'isAvailable' : IDL.Bool,
  });
  const KBArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'viewCount' : IDL.Nat,
    'category' : KnowledgeCategory,
  });
  const ChatTier = IDL.Variant({
    'sponsorship' : IDL.Null,
    'premium' : IDL.Null,
    'basic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'isTechnician' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const ChatFeedback = IDL.Record({
    'customer' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'comment' : IDL.Text,
    'sessionId' : IDL.Nat,
    'rating' : IDL.Int,
  });
  const LoginEvent = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'status' : PaymentStatus,
    'customer' : IDL.Principal,
    'currency' : IDL.Text,
    'paymentId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const ToggleStatus = IDL.Variant({
    'disabled' : IDL.Null,
    'enabled' : IDL.Null,
    'notRequested' : IDL.Null,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PaymentToggleState = IDL.Record({
    'technician' : IDL.Principal,
    'active' : IDL.Bool,
    'toggleEnabled' : IDL.Bool,
    'customer' : IDL.Principal,
    'paymentRequested' : IDL.Bool,
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const MessageStatus = IDL.Variant({
    'success' : IDL.Null,
    'failed' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addTicketFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTechnician' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createKBArticle' : IDL.Func(
        [IDL.Text, KnowledgeCategory, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createPaymentRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'createSupportCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSupportTicket' : IDL.Func([IDL.Principal], [SupportTicket], []),
    'deleteKBArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'endChatSession' : IDL.Func([IDL.Nat], [], []),
    'getAdminTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAllAvailableTechnicians' : IDL.Func(
        [],
        [IDL.Vec(TechnicianAvailability)],
        ['query'],
      ),
    'getAllKBArticles' : IDL.Func([], [IDL.Vec(KBArticle)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAnalyticsMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'resolutionRate' : IDL.Nat,
            'resolvedTickets' : IDL.Nat,
            'openTickets' : IDL.Nat,
            'totalTickets' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getArticlesByCategory' : IDL.Func(
        [KnowledgeCategory],
        [IDL.Vec(KBArticle)],
        ['query'],
      ),
    'getAvailableTiers' : IDL.Func([], [IDL.Vec(ChatTier)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatFeedback' : IDL.Func([IDL.Nat], [IDL.Opt(ChatFeedback)], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getKBArticle' : IDL.Func([IDL.Nat], [IDL.Opt(KBArticle)], ['query']),
    'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
    'getLoginEventsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'getMessagesBetweenUsers' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getPaymentRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentRecord)],
        ['query'],
      ),
    'getPersistentToggleState' : IDL.Func([IDL.Nat], [ToggleStatus], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportedCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTechnicianAvailability' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TechnicianAvailability)],
        ['query'],
      ),
    'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(SupportTicket)], ['query']),
    'getToggleState' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentToggleState)],
        ['query'],
      ),
    'getUserMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'incrementArticleViewCount' : IDL.Func([IDL.Nat], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesAsRead' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'markTicketMessagesAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchKBArticles' : IDL.Func([IDL.Text], [IDL.Vec(KBArticle)], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob)],
        [MessageStatus],
        [],
      ),
    'sendMessageForTicket' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [MessageStatus],
        [],
      ),
    'setAllTechniciansOffline' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setTechnicianAvailability' : IDL.Func([IDL.Bool], [], []),
    'setToggleState' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitRating' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'tierSelectionInfo' : IDL.Func(
        [IDL.Nat, ChatTier, IDL.Bool],
        [IDL.Record({ 'paymentStatus' : IDL.Bool, 'tier' : ChatTier })],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateKBArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, KnowledgeCategory, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatusOld], [], []),
    'updateTierSelection' : IDL.Func(
        [IDL.Nat, ChatTier],
        [ChatTier],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };