/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    displayName: string;
    isTechnician: boolean;
    avatar?: ExternalBlob;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaymentToggleState {
    technician: Principal;
    active: boolean;
    toggleEnabled: boolean;
    customer: Principal;
    paymentRequested: boolean;
    stripeSessionId?: string;
}
export interface KBArticle {
    id: bigint;
    title: string;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
    viewCount: bigint;
    category: KnowledgeCategory;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentRecord {
    status: PaymentStatus;
    customer: Principal;
    currency: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
}
export interface LoginEvent {
    name: string;
    role: string;
    email: string;
    timestamp: bigint;
    principalId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ChatFeedback {
    customer: Principal;
    submittedAt: bigint;
    comment: string;
    sessionId: bigint;
    rating: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type MessageStatus = {
    __kind__: "success";
    success: null;
} | {
    __kind__: "failed";
    failed: string;
};
export interface ChatMessage {
    content: string;
    messageId: bigint;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: bigint;
    delivered: boolean;
    attachment?: ExternalBlob;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface TechnicianAvailability {
    technician: Principal;
    lastUpdated: bigint;
    isAvailable: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SupportTicket {
    status: TicketStatusOld;
    technician: Principal;
    customer: Principal;
    messages: Array<ChatMessage>;
    createdAt: bigint;
    feedback?: {
        comment: string;
        rating: bigint;
    };
    ticketId: bigint;
    updatedAt: bigint;
}
export enum ChatTier {
    sponsorship = "sponsorship",
    premium = "premium",
    basic = "basic"
}
export enum KnowledgeCategory {
    NetworkConnectivity = "NetworkConnectivity",
    AccountPasswords = "AccountPasswords",
    GeneralSupport = "GeneralSupport",
    WindowsSupport = "WindowsSupport",
    SoftwareSupport = "SoftwareSupport",
    HardwareSupport = "HardwareSupport",
    PrintersPeripherals = "PrintersPeripherals"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TicketStatusOld {
    resolved = "resolved",
    open = "open",
    inProgress = "inProgress"
}
export enum ToggleStatus {
    disabled = "disabled",
    enabled = "enabled",
    notRequested = "notRequested"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addTicketFeedback(ticketId: bigint, rating: bigint, comment: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTechnician(ticketId: bigint, technician: Principal): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createKBArticle(title: string, category: KnowledgeCategory, body: string, tags: Array<string>): Promise<void>;
    createPaymentRecord(paymentId: string, amount: bigint, currency: string): Promise<void>;
    createSupportCheckoutSession(successUrl: string, cancelUrl: string): Promise<string>;
    createSupportTicket(technician: Principal): Promise<SupportTicket>;
    deleteKBArticle(articleId: bigint): Promise<void>;
    deleteMessage(messageId: bigint): Promise<void>;
    endChatSession(ticketId: bigint): Promise<void>;
    getAdminTickets(): Promise<Array<SupportTicket>>;
    getAllAvailableTechnicians(): Promise<Array<TechnicianAvailability>>;
    getAllKBArticles(): Promise<Array<KBArticle>>;
    getAllMessages(): Promise<Array<ChatMessage>>;
    getAnalyticsMetrics(): Promise<{
        resolutionRate: bigint;
        resolvedTickets: bigint;
        openTickets: bigint;
        totalTickets: bigint;
    }>;
    getArticlesByCategory(category: KnowledgeCategory): Promise<Array<KBArticle>>;
    getAvailableTiers(): Promise<Array<ChatTier>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatFeedback(sessionId: bigint): Promise<ChatFeedback | null>;
    getChatMessages(ticketId: bigint): Promise<Array<ChatMessage>>;
    getCustomerHistory(): Promise<Array<SupportTicket>>;
    getExpertHistory(): Promise<Array<SupportTicket>>;
    getKBArticle(articleId: bigint): Promise<KBArticle | null>;
    getLoginEvents(): Promise<Array<LoginEvent>>;
    getLoginEventsCSV(): Promise<string>;
    getMessagesBetweenUsers(user1: Principal, user2: Principal): Promise<Array<ChatMessage>>;
    getPaymentRecord(paymentId: string): Promise<PaymentRecord | null>;
    getPersistentToggleState(ticketId: bigint): Promise<ToggleStatus>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSupportedCurrencies(): Promise<Array<string>>;
    getTechnicianAvailability(technician: Principal): Promise<TechnicianAvailability | null>;
    getTicket(ticketId: bigint): Promise<SupportTicket | null>;
    getToggleState(ticketId: bigint): Promise<PaymentToggleState | null>;
    getUserMessages(): Promise<Array<ChatMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTickets(): Promise<Array<SupportTicket>>;
    incrementArticleViewCount(articleId: bigint): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markMessagesAsRead(user1: Principal, user2: Principal): Promise<void>;
    markTicketMessagesAsRead(ticketId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchKBArticles(searchTerm: string): Promise<Array<KBArticle>>;
    sendMessage(recipient: Principal, content: string, attachment: ExternalBlob | null): Promise<MessageStatus>;
    sendMessageForTicket(ticketId: bigint, content: string, attachment: ExternalBlob | null): Promise<MessageStatus>;
    setAllTechniciansOffline(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setTechnicianAvailability(isAvailable: boolean): Promise<void>;
    setToggleState(ticketId: bigint, toggleEnabled: boolean, paymentRequested: boolean, stripeSessionId: string | null): Promise<void>;
    submitRating(rating: bigint, comment: string): Promise<void>;
    tierSelectionInfo(ticketId: bigint, tier: ChatTier, paymentStatus: boolean): Promise<{
        paymentStatus: boolean;
        tier: ChatTier;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateKBArticle(articleId: bigint, title: string, category: KnowledgeCategory, body: string, tags: Array<string>): Promise<void>;
    updatePaymentStatus(paymentId: string, status: PaymentStatus): Promise<void>;
    updateTicketStatus(ticketId: bigint, status: TicketStatusOld): Promise<void>;
    updateTierSelection(ticketId: bigint, tier: ChatTier): Promise<ChatTier>;
}
import type { ChatFeedback as _ChatFeedback, ChatMessage as _ChatMessage, ChatTier as _ChatTier, ExternalBlob as _ExternalBlob, KBArticle as _KBArticle, KnowledgeCategory as _KnowledgeCategory, MessageStatus as _MessageStatus, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, PaymentToggleState as _PaymentToggleState, StripeSessionStatus as _StripeSessionStatus, SupportTicket as _SupportTicket, TechnicianAvailability as _TechnicianAvailability, TicketStatusOld as _TicketStatusOld, ToggleStatus as _ToggleStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addTicketFeedback(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTicketFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTicketFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTechnician(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTechnician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTechnician(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createKBArticle(arg0: string, arg1: KnowledgeCategory, arg2: string, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createKBArticle(arg0, to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKBArticle(arg0, to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async createPaymentRecord(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async createSupportCheckoutSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupportCheckoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupportCheckoutSession(arg0, arg1);
            return result;
        }
    }
    async createSupportTicket(arg0: Principal): Promise<SupportTicket> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupportTicket(arg0);
                return from_candid_SupportTicket_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupportTicket(arg0);
            return from_candid_SupportTicket_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteKBArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKBArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKBArticle(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async endChatSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endChatSession(arg0);
            return result;
        }
    }
    async getAdminTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTickets();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTickets();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAvailableTechnicians(): Promise<Array<TechnicianAvailability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableTechnicians();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableTechnicians();
            return result;
        }
    }
    async getAllKBArticles(): Promise<Array<KBArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKBArticles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKBArticles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsMetrics(): Promise<{
        resolutionRate: bigint;
        resolvedTickets: bigint;
        openTickets: bigint;
        totalTickets: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsMetrics();
            return result;
        }
    }
    async getArticlesByCategory(arg0: KnowledgeCategory): Promise<Array<KBArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTiers(): Promise<Array<ChatTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTiers();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTiers();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatFeedback(arg0: bigint): Promise<ChatFeedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatFeedback(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatFeedback(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerHistory(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpertHistory(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpertHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpertHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKBArticle(arg0: bigint): Promise<KBArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKBArticle(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKBArticle(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoginEvents(): Promise<Array<LoginEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoginEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoginEvents();
            return result;
        }
    }
    async getLoginEventsCSV(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoginEventsCSV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoginEventsCSV();
            return result;
        }
    }
    async getMessagesBetweenUsers(arg0: Principal, arg1: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesBetweenUsers(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesBetweenUsers(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentRecord(arg0: string): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecord(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecord(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersistentToggleState(arg0: bigint): Promise<ToggleStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentToggleState(arg0);
                return from_candid_ToggleStatus_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentToggleState(arg0);
            return from_candid_ToggleStatus_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupportedCurrencies(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportedCurrencies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportedCurrencies();
            return result;
        }
    }
    async getTechnicianAvailability(arg0: Principal): Promise<TechnicianAvailability | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicianAvailability(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicianAvailability(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicket(arg0: bigint): Promise<SupportTicket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicket(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicket(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToggleState(arg0: bigint): Promise<PaymentToggleState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToggleState(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToggleState(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMessages();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMessages();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTickets();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTickets();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementArticleViewCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementArticleViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementArticleViewCount(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markMessagesAsRead(arg0: Principal, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesAsRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesAsRead(arg0, arg1);
            return result;
        }
    }
    async markTicketMessagesAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTicketMessagesAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTicketMessagesAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchKBArticles(arg0: string): Promise<Array<KBArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKBArticles(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKBArticles(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: ExternalBlob | null): Promise<MessageStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
                return from_candid_MessageStatus_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
            return from_candid_MessageStatus_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessageForTicket(arg0: bigint, arg1: string, arg2: ExternalBlob | null): Promise<MessageStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageForTicket(arg0, arg1, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
                return from_candid_MessageStatus_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageForTicket(arg0, arg1, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
            return from_candid_MessageStatus_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAllTechniciansOffline(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllTechniciansOffline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllTechniciansOffline();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setTechnicianAvailability(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTechnicianAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTechnicianAvailability(arg0);
            return result;
        }
    }
    async setToggleState(arg0: bigint, arg1: boolean, arg2: boolean, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setToggleState(arg0, arg1, arg2, to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setToggleState(arg0, arg1, arg2, to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitRating(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1);
            return result;
        }
    }
    async tierSelectionInfo(arg0: bigint, arg1: ChatTier, arg2: boolean): Promise<{
        paymentStatus: boolean;
        tier: ChatTier;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.tierSelectionInfo(arg0, to_candid_ChatTier_n61(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tierSelectionInfo(arg0, to_candid_ChatTier_n61(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateKBArticle(arg0: bigint, arg1: string, arg2: KnowledgeCategory, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKBArticle(arg0, arg1, to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKBArticle(arg0, arg1, to_candid_KnowledgeCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTicketStatus(arg0: bigint, arg1: TicketStatusOld): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatusOld_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatusOld_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTierSelection(arg0: bigint, arg1: ChatTier): Promise<ChatTier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTierSelection(arg0, to_candid_ChatTier_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ChatTier_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTierSelection(arg0, to_candid_ChatTier_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ChatTier_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ChatMessage_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): Promise<ChatMessage> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ChatTier_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatTier): ChatTier {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_KBArticle_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KBArticle): KBArticle {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_KnowledgeCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeCategory): KnowledgeCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentToggleState_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentToggleState): PaymentToggleState {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_SupportTicket_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportTicket): Promise<SupportTicket> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatusOld_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatusOld): TicketStatusOld {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ToggleStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToggleStatus): ToggleStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        comment: string;
        rating: bigint;
    }]): {
    comment: string;
    rating: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatFeedback]): ChatFeedback | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KBArticle]): KBArticle | null {
    return value.length === 0 ? null : from_candid_KBArticle_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TechnicianAvailability]): TechnicianAvailability | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupportTicket]): Promise<SupportTicket | null> {
    return value.length === 0 ? null : await from_candid_SupportTicket_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentToggleState]): PaymentToggleState | null {
    return value.length === 0 ? null : from_candid_PaymentToggleState_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TicketStatusOld;
    technician: Principal;
    customer: Principal;
    messages: Array<_ChatMessage>;
    createdAt: bigint;
    feedback: [] | [{
            comment: string;
            rating: bigint;
        }];
    ticketId: bigint;
    updatedAt: bigint;
}): Promise<{
    status: TicketStatusOld;
    technician: Principal;
    customer: Principal;
    messages: Array<ChatMessage>;
    createdAt: bigint;
    feedback?: {
        comment: string;
        rating: bigint;
    };
    ticketId: bigint;
    updatedAt: bigint;
}> {
    return {
        status: from_candid_TicketStatusOld_n14(_uploadFile, _downloadFile, value.status),
        technician: value.technician,
        customer: value.customer,
        messages: await from_candid_vec_n16(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt,
        feedback: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.feedback)),
        ticketId: value.ticketId,
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    messageId: bigint;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: bigint;
    delivered: boolean;
    attachment: [] | [_ExternalBlob];
}): Promise<{
    content: string;
    messageId: bigint;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: bigint;
    delivered: boolean;
    attachment?: ExternalBlob;
}> {
    return {
        content: value.content,
        messageId: value.messageId,
        recipient: value.recipient,
        isRead: value.isRead,
        sender: value.sender,
        timestamp: value.timestamp,
        delivered: value.delivered,
        attachment: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.attachment))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
    viewCount: bigint;
    category: _KnowledgeCategory;
}): {
    id: bigint;
    title: string;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    updatedAt: bigint;
    viewCount: bigint;
    category: KnowledgeCategory;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        createdAt: value.createdAt,
        tags: value.tags,
        updatedAt: value.updatedAt,
        viewCount: value.viewCount,
        category: from_candid_KnowledgeCategory_n26(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    isTechnician: boolean;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    displayName: string;
    isTechnician: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        displayName: value.displayName,
        isTechnician: value.isTechnician,
        avatar: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    customer: Principal;
    currency: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
}): {
    status: PaymentStatus;
    customer: Principal;
    currency: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n41(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        currency: value.currency,
        paymentId: value.paymentId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    technician: Principal;
    active: boolean;
    toggleEnabled: boolean;
    customer: Principal;
    paymentRequested: boolean;
    stripeSessionId: [] | [string];
}): {
    technician: Principal;
    active: boolean;
    toggleEnabled: boolean;
    customer: Principal;
    paymentRequested: boolean;
    stripeSessionId?: string;
} {
    return {
        technician: value.technician,
        active: value.active,
        toggleEnabled: value.toggleEnabled,
        customer: value.customer,
        paymentRequested: value.paymentRequested,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.stripeSessionId))
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: boolean;
    tier: _ChatTier;
}): {
    paymentStatus: boolean;
    tier: ChatTier;
} {
    return {
        paymentStatus: value.paymentStatus,
        tier: from_candid_ChatTier_n29(_uploadFile, _downloadFile, value.tier)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
}): TicketStatusOld {
    return "resolved" in value ? TicketStatusOld.resolved : "open" in value ? TicketStatusOld.open : "inProgress" in value ? TicketStatusOld.inProgress : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NetworkConnectivity: null;
} | {
    AccountPasswords: null;
} | {
    GeneralSupport: null;
} | {
    WindowsSupport: null;
} | {
    SoftwareSupport: null;
} | {
    HardwareSupport: null;
} | {
    PrintersPeripherals: null;
}): KnowledgeCategory {
    return "NetworkConnectivity" in value ? KnowledgeCategory.NetworkConnectivity : "AccountPasswords" in value ? KnowledgeCategory.AccountPasswords : "GeneralSupport" in value ? KnowledgeCategory.GeneralSupport : "WindowsSupport" in value ? KnowledgeCategory.WindowsSupport : "SoftwareSupport" in value ? KnowledgeCategory.SoftwareSupport : "HardwareSupport" in value ? KnowledgeCategory.HardwareSupport : "PrintersPeripherals" in value ? KnowledgeCategory.PrintersPeripherals : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sponsorship: null;
} | {
    premium: null;
} | {
    basic: null;
}): ChatTier {
    return "sponsorship" in value ? ChatTier.sponsorship : "premium" in value ? ChatTier.premium : "basic" in value ? ChatTier.basic : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disabled: null;
} | {
    enabled: null;
} | {
    notRequested: null;
}): ToggleStatus {
    return "disabled" in value ? ToggleStatus.disabled : "enabled" in value ? ToggleStatus.enabled : "notRequested" in value ? ToggleStatus.notRequested : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n47(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    failed: string;
}): {
    __kind__: "success";
    success: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Promise<Array<ChatMessage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ChatMessage_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportTicket>): Promise<Array<SupportTicket>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SupportTicket_n12(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KBArticle>): Array<KBArticle> {
    return value.map((x)=>from_candid_KBArticle_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatTier>): Array<ChatTier> {
    return value.map((x)=>from_candid_ChatTier_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ChatTier_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatTier): _ChatTier {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_KnowledgeCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnowledgeCategory): _KnowledgeCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatusOld_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatusOld): _TicketStatusOld {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n56(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    isTechnician: boolean;
    avatar?: ExternalBlob;
}): Promise<{
    displayName: string;
    isTechnician: boolean;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        displayName: value.displayName,
        isTechnician: value.isTechnician,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n56(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnowledgeCategory): {
    NetworkConnectivity: null;
} | {
    AccountPasswords: null;
} | {
    GeneralSupport: null;
} | {
    WindowsSupport: null;
} | {
    SoftwareSupport: null;
} | {
    HardwareSupport: null;
} | {
    PrintersPeripherals: null;
} {
    return value == KnowledgeCategory.NetworkConnectivity ? {
        NetworkConnectivity: null
    } : value == KnowledgeCategory.AccountPasswords ? {
        AccountPasswords: null
    } : value == KnowledgeCategory.GeneralSupport ? {
        GeneralSupport: null
    } : value == KnowledgeCategory.WindowsSupport ? {
        WindowsSupport: null
    } : value == KnowledgeCategory.SoftwareSupport ? {
        SoftwareSupport: null
    } : value == KnowledgeCategory.HardwareSupport ? {
        HardwareSupport: null
    } : value == KnowledgeCategory.PrintersPeripherals ? {
        PrintersPeripherals: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatTier): {
    sponsorship: null;
} | {
    premium: null;
} | {
    basic: null;
} {
    return value == ChatTier.sponsorship ? {
        sponsorship: null
    } : value == ChatTier.premium ? {
        premium: null
    } : value == ChatTier.basic ? {
        basic: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatusOld): {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == TicketStatusOld.resolved ? {
        resolved: null
    } : value == TicketStatusOld.open ? {
        open: null
    } : value == TicketStatusOld.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
